// download-font.js
// Run once after npm install to download the Telugu font for offline use
const https = require('https');
const http = require('http');
const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, 'src', 'telugu-font.js');

// If already downloaded, skip
if (fs.existsSync(outPath)) {
  console.log('Telugu font already downloaded.');
  process.exit(0);
}

console.log('Downloading Telugu font from Google Fonts...');

// Step 1: Get the CSS to find the font URL
const cssUrl = 'https://fonts.googleapis.com/css2?family=Noto+Serif+Telugu&display=swap';
const options = {
  headers: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
  }
};

function get(url, opts, cb) {
  const mod = url.startsWith('https') ? https : http;
  mod.get(url, opts, (res) => {
    if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
      return get(res.headers.location, opts, cb);
    }
    let data = [];
    res.on('data', chunk => data.push(chunk));
    res.on('end', () => cb(null, Buffer.concat(data)));
  }).on('error', cb);
}

get(cssUrl, options, (err, cssData) => {
  if (err) {
    console.log('Could not download font (no internet). Telugu text will be skipped in PDFs.');
    // Write empty font file so app still works
    fs.writeFileSync(outPath, 'export const teluguFontBase64 = null;\n');
    return;
  }

  const css = cssData.toString();
  // Find TTF or WOFF URL
  const match = css.match(/url\(([^)]+\.(ttf|woff2?)[^)]*)\)/);
  if (!match) {
    console.log('Font URL not found in CSS.');
    fs.writeFileSync(outPath, 'export const teluguFontBase64 = null;\n');
    return;
  }

  const fontUrl = match[1].replace(/['"]/g, '');
  console.log('Downloading font file:', fontUrl.substring(0, 60) + '...');

  get(fontUrl, options, (err2, fontData) => {
    if (err2 || fontData.length < 10000) {
      console.log('Font download failed. Telugu text will be skipped.');
      fs.writeFileSync(outPath, 'export const teluguFontBase64 = null;\n');
      return;
    }

    const base64 = fontData.toString('base64');
    const ext = fontUrl.includes('.ttf') ? 'ttf' : 'woff2';
    fs.writeFileSync(outPath,
      `// Auto-generated by download-font.js\n` +
      `// Telugu font embedded for offline PDF generation\n` +
      `export const teluguFontBase64 = '${base64}';\n` +
      `export const teluguFontExt = '${ext}';\n`
    );
    console.log(`Telugu font saved (${Math.round(fontData.length/1024)}KB). Telugu text will appear in PDFs.`);
  });
});
